name: Basic Code Validation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Simple Python syntax check
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Basic Python validation
        run: |
          python -m py_compile $(find . -name "*.py")
          
      # Simple file existence checks
      - name: Verify critical files exist
        run: |
          echo "Checking critical files..."
          test -f README.md && echo "README.md exists" || exit 1
          test -d terraform && echo "Terraform directory exists" || exit 1
          test -d src && echo "Source directory exists" || exit 1
